### ISSUE TITLE
Application fixes

### ISSUE THREAD

**Issue by omkarmoghe** [mhacks/MHacks-Website#15]
- [x] improve UI for cortex
- [x] submit/save functionality
- [x] improve UI for date fields
- [x] check and fix all email templates
- [x] fix UI for after registration email verification screen
- [x] show thanks for applying thing after submitted (see post registration thing ^)
- [x] fix dashboard UI and messages
- [x] fix adding the file to a saved application
- [x] fix error message UI (reach goal)

**Comment by anksh** [comment]
I think it would be best to split the single checkbox for the questions into 'Yes' and 'No' checkboxes for clarity.

ie "Are you a high schooler" [  ] Yes [  ] No
Instead of the current, semi-ambiguous "Are you a high schooler" [  ]

**Comment by manavgabhawala** [comment]
@anksh if you think switching to Yes No is pretty important, please can you make another issue, closing this one for now since everything else is fixed and we don't want to end up in a situation with "catch all" issue. (also see the new fixed UI for the application form, the layout may have reduced the original ambiguity that existed)
